### ISSUE TITLE
Add ReLU as option in convert.activation.function

### ISSUE THREAD

**Issue by vnijs** [bips-hb/neuralnet#18]
Would it be possible to add ReLU as an alternative to `convert.activation.function`?

**Comment by mnwright** [comment]
Yes, that should be possible.

Btw., we cannot use it as a simple custom activation function as in
`neuralnet(Species ~ ., iris, linear.output = FALSE, act.fct = function(x) log(1 + exp(x)))`
because the ReLu is not differentiable at 0.

**Comment by mnwright** [comment]
Added in #19. However, with `linear.output = FALSE` (classification), the activation function is also applied to the output layer, which makes no sense for the ReLu. 

We could always use a sigmoid for the output layer instead of the selected activation function.

**Comment by vnijs** [comment]
Thank you @mnwright! Would it be an option to add an argument for the activation function to apply to the output layer perhaps that defaults to "logistic" for classification problems? Or what about allowing the user to specify a character vector of activation functions? If only one element is supplied it is used throughout. However, if two are specified the first is used for the hidden layer(s) and the last element is used for the output layer?

**Comment by mnwright** [comment]
Merged. Added an argument `output.act.fct` with default `"logistic"`, that is used if `linear.output = FALSE`. Remember to scale your data before using the ReLu. Example: 

````
library(neuralnet)
dat <- iris
dat[, -5] <- scale(dat[, -5])
nn <- neuralnet(Species ~ ., dat, linear.output = FALSE, act.fct = "relu")
````

**Comment by vnijs** [comment]
Nice! Thanks @mnwright

**Comment by alexsiormpas** [comment]
I'm doing regression and would like to apply relu as the activation function. Will this code work:
neuralnet(desesnetrev ~ . ,
                data=Data_scaled, 
                hidden=7,
                algorithm = "rprop+",
                act.fct = "relu",
                linear.output=TRUE,
                threshold=0.05)

**Comment by mnwright** [comment]
Yes, that should work.

**Comment by Davidowa** [comment]
Hello @mnwright ,
I'm just trying yo use the relu function as follows 

```
# creating training data set
data <- read.csv(file = 'metrics.csv')
training_set <- data[2:5]
# creating test set
dataTest <- read.csv(file = 'metricsTest.csv')
test_set = dataTest[2:4]
# create the NN model with 2 hidden layers of 50 neurons each
nn=neuralnet(Result~.,data=training_set, hidden=c(50,50),act.fct = "relu", linear.output = TRUE)
```
data is as follows
```
> data
  X     DTWx     DTWy      DTWz Result
1 1 46.70000 185.5600 117.25000      0
2 2 87.01000  87.4000  89.18000      0
3 3 15.33000  44.8700  32.20000      1
4 4 10.26000  95.8500  19.51000      1
5 5  6.87000 159.3500  32.91000      0
6 6 11.90912 111.2236  20.33453      1
```
But i get the following error
```
Error: Unknown activation function.
```
I hope you can help me with this issue. Thanks in advance for your help

**Comment by nba2020** [comment]
@Davidowa maybe installing the GitHub version of the package can make relu function available
`devtools::install_github("bips-hb/neuralnet”)`
I remember facing a similar issue a few months ago
