### ISSUE TITLE
Possible bug in the names of the response variable of the nn object

### ISSUE THREAD

**Issue by hlfernandez** [bips-hb/neuralnet#29]
Dear **neuralnet** developers,

I have found a possible bug in the names of the response variable of the nn object. Consider the following test dataset and simple model:
```
A=c(20,10,30,20,80,30)
B=c(90,20,40,50,50,80)
Response=c("control","cancer","cancer","cancer","control","control")
data=data.frame(A,B,Response)

nn=neuralnet(Response~A+B, data=data, hidden=3,act.fct = "logistic", linear.output = FALSE)
```

Now, if we look at the response variable and compare it with the actual Response values it can be seen that the column names are inverted, because when the row is "control" it always appears a "FALSE" in the corresponding "control" column: 
```
> cbind(nn$response, as.character(data$Response))
  control cancer           
1 "FALSE" "TRUE"  "control"
2 "TRUE"  "FALSE" "cancer" 
3 "TRUE"  "FALSE" "cancer" 
4 "TRUE"  "FALSE" "cancer" 
5 "FALSE" "TRUE"  "control"
6 "FALSE" "TRUE"  "control"
```

However, if the data is sorted by the Response column (so that cancer appears first), then the response object is right:
```
data.sorted <- data[order(data$Response), ]
nn2=neuralnet(Response~A+B,data=data.sorted, hidden=3,act.fct = "logistic", linear.output = FALSE)
> cbind(nn2$response, as.character(data.sorted$Response))
  cancer  control          
1 "TRUE"  "FALSE" "cancer" 
2 "TRUE"  "FALSE" "cancer" 
3 "TRUE"  "FALSE" "cancer" 
4 "FALSE" "TRUE"  "control"
5 "FALSE" "TRUE"  "control"
6 "FALSE" "TRUE"  "control"
```

Thank you in advance.

Regards,
  Hugo.

**Comment by mnwright** [comment]
Thanks, fixed.
